#!/bin/sh

sxhkd &
#exec setxkbmap dk &
numlockx &

bspc config border_width        1
bspc config window_gap          45



#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor LVDS1 -d DEV WEB TERM FILES RAND MEDIA SOC REMOTE
#bspc monitor VGA1 -d EXTR
#xrandr --output VGA1 --auto --left-of monitor --rotate left
#xrandr --output VGA1 --mode 1050x1680 --rotate right --left-of LVDS1

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d {DEV,WEB,TERM,FILES,RAND,MEDIA,SOC,TERM2,→REMOTE}
    let i++
done
NMON=$i
unset i
#bspc monitor VGA1 -d EXTR
bspc config top_padding 14 

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


# Rules
bspc rule -a Skype pseudo_tiled=on
bspc rule -a rofi pseudo_tiled=on
bspc rule -a Infinit pseudo_tiled=on
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a sun-awt-X11-XFramePeer pseudo_tiled=on
bspc rule -a Renoise pseudo_tiled=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a feh floating=on manage=off



#panel &

compton &
radiotray &
nm-applet &
lxappearance &


#feh --bg-fill /home/null/Pictures/wallpapers/papers.co-mn32-forest-wood-fog-flare-nature-green-25-wallpaper.jpg &
#feh --bg-scale /home/null/Pictures/wallpapers/overflow.png
#feh --bg-center /home/null/Pictures/wallpapers/grass_fog_light_dark_background_49885_1920x1080.jpg &
#feh --bg-center /home/null/Pictures/wallpapers/fHFDkjY_copy.jpg
#feh --bg-scale /home/null/Pictures/wallpapers/papers.co-mo50-forest-green-nature-tree-jonas-nilsson-lee-25-wallpaper_deux.jpg &
#feh --bg-scale /home/null/Pictures/wallpapers/1g8pWTZ.jpg &


timeout 3 screen -S rightpanel -dm /home/null/.bin/panel/dzen2_bar.sh &
timeout 4 screen -S tray -dm  /home/null/.bin/panel/tray.sh &
timeout 5 feh --bg-scale /home/null/Pictures/wallpapers/greenfield.jpg &
timeout 8 screen -S panel -dm  /home/null/.bin/panel/panel &
